### PR TITLE
Reject invalid dates

### PR DESCRIPTION
**Pull request by erikkemperman**
cf. https://github.com/gulpjs/vinyl-fs/issues/191

### CODE REVIEW

**Comment by phated** [comment]
This would normalize to a timestamp.  So the method name would be weird.  I think, based on #4, that it would take lenient input (dates, numbers, number objects) and return a Date object.  We could mirror that with a `.timestamp()` method that returns the number timestamp.

Also, do you think we should use the `vali-date` module to do date object validation?

**Comment by erikkemperman** [comment]
This PR doesn't change the return type, just the boolean function to decide accept/reject of the given value. In response to the vinyl-fs issue about consistent dates.

Looking at this though, got me thinking about lenient in / strict out, and then I made that issue here, so I guess my timing was confusing but this PR is separate.

I have something working for that other issue as well but would like to add a bit more.

**Comment by erikkemperman** [comment]
PS vali-date would not be necessary I think. Wasteful even, because it checks validity by actually coercing to Date... Which it then throws away and returns true or false. For us to coerce again.

**Comment by phated** [comment]
Oh yeah, I was thinking about that method incorrectly.  This looks good.  I'll merge and bump patch version.

**Comment by erikkemperman** [comment]
Thanks!

**Pull request merged**
